# Generated by Django 4.0.4 on 2022-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Class', models.IntegerField()),
                ('Student_Age', models.IntegerField()),
                ('Student_Section', models.CharField(max_length=20)),
                ('Student_Sex', models.CharField(max_length=20)),
            ],
        ),
    ]
